management:
  endpoints:
    web:
      exposure:
        include: "*"

me:
  polynom:
    polycloud:
      apps:
        example:
          enabled: true
        files:
          enabled: true
        calendar:
          enabled: true
        auth:
          stub:
            enabled: true

# Enable debug logging for everything polycloud
logging:
  level:
    me.polynom.polycloud: debug
