name: Lint/Check Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  ci:
    name: Gradle Spotless and Detekt
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run ci
        run: ./gradlew ci
